import type { Metadata } from "next";
import { Providers } from "@/app/providers";
import NavBar from "@/components/NavBar";
import { Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang='en'>
        <body>
            <Providers>
              <Container>
                <NavBar />
                {children}
              </Container>
            </Providers>
        </body>
      </html>
  );
}
